# Generated by Django 5.0.2 on 2024-07-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_product_sku_product_is_variant_product_skus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='google_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='orig_path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
