# Generated by Django 5.0.7 on 2024-07-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.F('site_id'), models.F('orig_id'), name='site_orig_index'),
        ),
    ]
