# Generated by Django 5.0.7 on 2024-07-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_product_site_orig_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='site_orig_index',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(models.F('orig_id'), name='orig_index'),
        ),
    ]
