# Generated by Django 5.0.7 on 2024-07-21 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_remove_product_site_orig_index_product_orig_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='orig_index',
        ),
    ]
