# Generated by Django 5.0.7 on 2024-08-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_remove_product_orig_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deal',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
